### PR TITLE
use volmgr blueprint

### PR DESCRIPTION
**Pull request by MarkRatjens**

### CODE REVIEW

**Review by jvodan — COMMENTED** [review]
/var/spool is a fixed dir on just about every unix install  
Who is spool user?

**Comment by MarkRatjens** [comment]
^^spool.user^^ picks up the user variable from the spool binding

**Comment by MarkRatjens** [comment]
what is the action required for /var/spool ?

**Comment by jvodan** [comment]
The path is /var/spool/postfix/ always
The mount is to /var/spool/postfix
I dont understand how the parent dir of the mount figures in any of the params

**Comment by jvodan** [comment]
In case you missed this in slack:v2 
The path is /var/spool/postfix/ always
The mount is to /var/spool/postfix
I dont understand how the parent dir of the mount figures in any of the params
there are several other unix system dirs under /var/spool/

**Review by jvodan — APPROVED** [review]

**Pull request merged**
